2024-02-19 17:03:30,059 INFO    Thread-14 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa'}
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170330-4ij6bwge/logs/debug.log
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170330-4ij6bwge/logs/debug-internal.log
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4ccc0f1960>
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'dk': 32, 'dv': 32, 'epochs': 100, 'features_length': 32, 'learning_rate': 0.00979722097568321, 'num_blocks': 2, 'num_heads': 1, 'optimizer': 'adam'}
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:03:30,060 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:03:30,065 INFO    Thread-14 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:03:30,065 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:03:30,080 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:03:30,081 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:03:30,081 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:03:30,093 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:03:30,268 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:03:30,299 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:03:30,299 INFO    Thread-14 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:03:31,630 INFO    MainThread:23829 [pyagent.py:run():324] Starting sweep agent: entity=None, project=None, count=2
2024-02-19 17:03:34,091 ERROR   Thread-14 (_run_job):23829 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 846, in init
    run._on_start()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2280, in _on_start
    self._header(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3459, in _header
    Run._header_wandb_version_info(settings=settings, printer=printer)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 3492, in _header_wandb_version_info
    printer.display(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 68, in display
    self._display(text, level=level, default_text=default_text)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 248, in _display
    self._display_fn_mapping(level)(text)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py", line 81, in display_html
    return display(HTML(html))
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/IPython/core/display_functions.py", line 305, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/IPython/core/display_functions.py", line 93, in publish_display_data
    display_pub.publish(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 483, in publish
    ipython.display_pub._orig_publish(data, metadata=metadata, **kwargs)
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 103, in publish
    self._flush_streams()
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 66, in _flush_streams
    sys.stdout.flush()
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 604, in flush
    self.pub_thread.schedule(self._flush)
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1184, in init
    getcaller()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 855, in getcaller
    print("Problem at:", src, line, func)
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 694, in write
    self._schedule_flush()
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 590, in _schedule_flush
    self.pub_thread.schedule(_schedule_in_thread)
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/ipykernel/iostream.py", line 267, in schedule
    self._event_pipe.send(b"")
  File "/teamspace/studios/this_studio/.local/lib/python3.10/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
2024-02-19 17:03:34,139 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/4ij6bwge
2024-02-19 17:03:34,140 INFO    Thread-14 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:03:34,140 INFO    Thread-14 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:03:34,140 INFO    Thread-14 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:03:34,140 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 17:03:34,140 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:03:34,140 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:03:35,948 WARNING MsgRouterThr:23829 [router.py:message_loop():77] message_loop has been closed
2024-02-19 17:03:37,119 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa', 'root_dir': '/teamspace/studios/this_studio/A2_Transformer', 'sweep_id': 'd2f9067v', 'run_id': 'kteqqrmb', 'sweep_param_path': '/teamspace/studios/this_studio/A2_Transformer/wandb/sweep-d2f9067v/config-kteqqrmb.yaml'}
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170337-kteqqrmb/logs/debug.log
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170337-kteqqrmb/logs/debug-internal.log
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4cc40d29e0>
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:03:37,120 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {'dk': 32, 'dv': 64, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.005550070515547667, 'num_blocks': 3, 'num_heads': 2, 'optimizer': 'sgd'}
config: {}
2024-02-19 17:03:37,121 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:03:37,121 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:03:37,125 INFO    Thread-20 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:03:37,125 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:03:37,137 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'dk': 32, 'dv': 64, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.005550070515547667, 'num_blocks': 3, 'num_heads': 2, 'optimizer': 'sgd'}
2024-02-19 17:03:37,138 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:03:37,138 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:03:37,138 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:03:37,147 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:03:37,269 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:03:37,296 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:03:37,297 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:03:40,142 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:03:40,142 INFO    Thread-14 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:03:41,244 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:03:41,245 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:03:41,245 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:03:41,245 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:03:41,246 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:03:41,249 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/kteqqrmb
2024-02-19 17:03:41,249 INFO    Thread-20 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:03:41,249 INFO    Thread-20 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:03:41,249 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:03:41,249 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 17:03:41,250 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:03:41,250 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:03:43,957 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:03:43,957 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:03:43,961 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:03:46,985 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa'}
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170346-viluf2ui/logs/debug.log
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170346-viluf2ui/logs/debug-internal.log
2024-02-19 17:03:46,986 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4cc40f9a80>
2024-02-19 17:03:46,987 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:03:46,987 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'dk': 32, 'dv': 64, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.005550070515547667, 'num_blocks': 3, 'num_heads': 2, 'optimizer': 'sgd'}
2024-02-19 17:03:46,987 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:03:46,987 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:03:46,990 INFO    Thread-20 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:03:46,990 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:03:47,001 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:03:47,001 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:03:47,001 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:03:47,010 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:03:47,221 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:03:47,248 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:03:47,248 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:03:51,180 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:03:51,181 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:03:51,181 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:03:51,182 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:03:51,182 INFO    Thread-20 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:03:51,243 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'trainable_params': 113211, 'non_trainable_params': 0, 'total_params': 113211}
2024-02-19 17:03:51,359 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/viluf2ui
2024-02-19 17:03:51,360 INFO    Thread-20 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:03:51,360 INFO    Thread-20 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:03:51,360 INFO    Thread-20 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:03:51,360 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 1
2024-02-19 17:03:51,360 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:03:51,360 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:03:57,798 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:03:57,799 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:03:57,803 INFO    Thread-20 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:03:57,837 ERROR   MainThread:23829 [pyagent.py:_run_jobs_from_queue():236] Run kteqqrmb errored:
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/tmp/ipykernel_23829/1136002265.py", line 36, in cross_validate
    history = train_sweep_arch2(
  File "/tmp/ipykernel_23829/2550959825.py", line 45, in train_sweep_arch2
    history = train(
  File "/tmp/ipykernel_23829/2815199032.py", line 40, in train
    output = model(input)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_23829/4031563196.py", line 181, in forward
    cls_token = torch.zeros(x.size(0), 1, self.input_dim - 1).to(x.device)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'transformer' object has no attribute 'input_dim'

2024-02-19 17:04:03,847 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:04:03,847 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa', 'run_id': 'kc33ma0i', 'sweep_param_path': 'wandb/sweep-d2f9067v/config-kc33ma0i.yaml', 'sweep_id': 'd2f9067v'}
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170403-kc33ma0i/logs/debug.log
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170403-kc33ma0i/logs/debug-internal.log
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4ccc0dc400>
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {'dk': 64, 'dv': 32, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.007864930937853391, 'num_blocks': 2, 'num_heads': 2, 'optimizer': 'adam'}
config: {}
2024-02-19 17:04:03,848 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:04:03,849 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:04:03,853 INFO    Thread-26 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:04:03,854 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:04:03,866 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'dk': 64, 'dv': 32, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.007864930937853391, 'num_blocks': 2, 'num_heads': 2, 'optimizer': 'adam'}
2024-02-19 17:04:03,867 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:04:03,867 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:04:03,867 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:04:03,876 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:04:04,045 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:04:04,077 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:04:04,077 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:04:08,065 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:04:08,066 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:04:08,066 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:04:08,066 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:04:08,067 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:04:08,070 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/kc33ma0i
2024-02-19 17:04:08,070 INFO    Thread-26 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:04:08,070 INFO    Thread-26 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:04:08,070 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:04:08,070 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 17:04:08,070 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:04:08,070 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:04:10,750 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:04:10,753 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:04:10,756 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:04:13,829 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa'}
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170413-qm6rl3x8/logs/debug.log
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170413-qm6rl3x8/logs/debug-internal.log
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4cbe6b7670>
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'dk': 64, 'dv': 32, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.007864930937853391, 'num_blocks': 2, 'num_heads': 2, 'optimizer': 'adam'}
2024-02-19 17:04:13,830 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:04:13,831 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:04:13,834 INFO    Thread-26 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:04:13,834 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:04:13,845 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:04:13,846 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:04:13,846 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:04:13,857 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:04:14,059 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:04:14,094 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:04:14,094 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:04:17,997 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:04:17,998 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:04:17,998 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:04:17,998 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:04:17,999 INFO    Thread-26 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:04:18,043 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'trainable_params': 47483, 'non_trainable_params': 0, 'total_params': 47483}
2024-02-19 17:04:18,194 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/qm6rl3x8
2024-02-19 17:04:18,194 INFO    Thread-26 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:04:18,194 INFO    Thread-26 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:04:18,194 INFO    Thread-26 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:04:18,194 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 1
2024-02-19 17:04:18,194 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:04:18,195 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:04:22,634 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:04:22,635 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:04:22,639 INFO    Thread-26 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:04:22,672 ERROR   MainThread:23829 [pyagent.py:_run_jobs_from_queue():236] Run kc33ma0i errored:
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/tmp/ipykernel_23829/1136002265.py", line 36, in cross_validate
    history = train_sweep_arch2(
  File "/tmp/ipykernel_23829/2550959825.py", line 45, in train_sweep_arch2
    history = train(
  File "/tmp/ipykernel_23829/2815199032.py", line 40, in train
    output = model(input)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_23829/4031563196.py", line 178, in forward
    x = self.cnn_features(x)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_23829/4031563196.py", line 24, in forward
    x = F.relu(x)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/functional.py", line 1473, in relu
    result = torch.relu(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 223.06 MiB is free. Process 70288 has 14.53 GiB memory in use. Of the allocated memory 14.37 GiB is allocated by PyTorch, and 35.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-02-19 17:04:22,947 INFO    MainThread:23829 [pyagent.py:run():324] Starting sweep agent: entity=None, project=None, count=2
2024-02-19 17:04:25,935 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:04:25,935 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa', 'root_dir': '/teamspace/studios/this_studio/A2_Transformer', 'sweep_id': 'ogzlre15', 'run_id': 'j3v9jyju', 'sweep_param_path': '/teamspace/studios/this_studio/A2_Transformer/wandb/sweep-ogzlre15/config-j3v9jyju.yaml'}
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170425-j3v9jyju/logs/debug.log
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170425-j3v9jyju/logs/debug-internal.log
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4cc5719690>
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:04:25,936 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {'dk': 32, 'dv': 64, 'epochs': 100, 'features_length': 32, 'learning_rate': 0.007086329992084786, 'num_blocks': 3, 'num_heads': 4, 'optimizer': 'sgd'}
config: {}
2024-02-19 17:04:25,937 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:04:25,937 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:04:25,942 INFO    Thread-32 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:04:25,943 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:04:25,959 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'dk': 32, 'dv': 64, 'epochs': 100, 'features_length': 32, 'learning_rate': 0.007086329992084786, 'num_blocks': 3, 'num_heads': 4, 'optimizer': 'sgd'}
2024-02-19 17:04:25,960 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:04:25,960 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:04:25,960 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:04:25,997 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:04:26,430 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:04:26,458 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:04:26,458 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:04:30,255 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:04:30,255 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:04:30,256 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:04:30,257 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:04:30,257 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:04:30,261 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/j3v9jyju
2024-02-19 17:04:30,261 INFO    Thread-32 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:04:30,261 INFO    Thread-32 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:04:30,262 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:04:30,262 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 17:04:30,262 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:04:30,262 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:04:33,102 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:04:33,103 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:04:33,106 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:04:36,250 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:04:36,251 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:04:36,251 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:04:36,251 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:04:36,251 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa'}
2024-02-19 17:04:36,251 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:04:36,251 INFO    Thread-32 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:04:36,252 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170436-dgx0l3hh/logs/debug.log
2024-02-19 17:04:36,252 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170436-dgx0l3hh/logs/debug-internal.log
2024-02-19 17:04:36,252 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4cc562be50>
2024-02-19 17:04:36,252 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:04:36,252 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'dk': 32, 'dv': 64, 'epochs': 100, 'features_length': 32, 'learning_rate': 0.007086329992084786, 'num_blocks': 3, 'num_heads': 4, 'optimizer': 'sgd'}
2024-02-19 17:04:36,252 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:04:36,252 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:04:36,256 INFO    Thread-32 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:04:36,257 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:04:36,270 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:04:36,270 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:04:36,270 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:04:36,280 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:04:36,517 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:04:36,544 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:04:36,544 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:04:40,347 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:04:40,347 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:04:40,347 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:04:40,347 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:04:40,348 INFO    Thread-32 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:04:40,407 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'trainable_params': 199499, 'non_trainable_params': 0, 'total_params': 199499}
2024-02-19 17:04:40,537 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/dgx0l3hh
2024-02-19 17:04:40,537 INFO    Thread-32 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:04:40,537 INFO    Thread-32 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:04:40,537 INFO    Thread-32 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:04:40,537 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 1
2024-02-19 17:04:40,537 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:04:40,538 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:04:45,097 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:04:45,099 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:04:45,108 INFO    Thread-32 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:04:45,143 ERROR   MainThread:23829 [pyagent.py:_run_jobs_from_queue():236] Run j3v9jyju errored:
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/tmp/ipykernel_23829/1136002265.py", line 36, in cross_validate
    history = train_sweep_arch2(
  File "/tmp/ipykernel_23829/2550959825.py", line 45, in train_sweep_arch2
    history = train(
  File "/tmp/ipykernel_23829/2815199032.py", line 40, in train
    output = model(input)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_23829/4031563196.py", line 178, in forward
    x = self.cnn_features(x)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_23829/4031563196.py", line 19, in forward
    x = self.conv1(x)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 203.06 MiB is free. Process 70288 has 14.55 GiB memory in use. Of the allocated memory 14.39 GiB is allocated by PyTorch, and 36.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

2024-02-19 17:04:50,414 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:04:50,414 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:04:50,414 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:04:50,414 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:04:50,414 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa', 'run_id': '269qkpua', 'sweep_param_path': 'wandb/sweep-ogzlre15/config-269qkpua.yaml', 'sweep_id': 'ogzlre15'}
2024-02-19 17:04:50,414 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170450-269qkpua/logs/debug.log
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170450-269qkpua/logs/debug-internal.log
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4cc565fbb0>
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {'dk': 32, 'dv': 32, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.008045014585191029, 'num_blocks': 2, 'num_heads': 4, 'optimizer': 'sgd'}
config: {}
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:04:50,415 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:04:50,421 INFO    Thread-37 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:04:50,421 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:04:50,436 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'dk': 32, 'dv': 32, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.008045014585191029, 'num_blocks': 2, 'num_heads': 4, 'optimizer': 'sgd'}
2024-02-19 17:04:50,437 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:04:50,437 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:04:50,438 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:04:50,451 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:04:50,630 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:04:50,666 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:04:50,666 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:04:54,429 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:04:54,429 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:04:54,429 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:04:54,430 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:04:54,430 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:04:54,434 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/269qkpua
2024-02-19 17:04:54,434 INFO    Thread-37 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:04:54,434 INFO    Thread-37 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:04:54,434 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:04:54,435 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 17:04:54,435 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:04:54,435 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:05:03,466 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:05:03,467 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:05:03,470 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:05:06,571 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Configure stats pid to 23829
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/.config/wandb/settings
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from /teamspace/studios/this_studio/A2_Transformer/wandb/settings
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DL_A2_Arch2_cls', 'entity': 'khadgaa'}
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_log_setup():526] Logging user logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170506-f1j1yu4d/logs/debug.log
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_log_setup():527] Logging internal logs to /teamspace/studios/this_studio/A2_Transformer/wandb/run-20240219_170506-f1j1yu4d/logs/debug-internal.log
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4cc56e1180>
2024-02-19 17:05:06,572 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():566] calling init triggers
2024-02-19 17:05:06,573 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'dk': 32, 'dv': 32, 'epochs': 100, 'features_length': 16, 'learning_rate': 0.008045014585191029, 'num_blocks': 2, 'num_heads': 4, 'optimizer': 'sgd'}
2024-02-19 17:05:06,573 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():616] starting backend
2024-02-19 17:05:06,573 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():620] setting up manager
2024-02-19 17:05:06,576 INFO    Thread-37 (_run_job):23829 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-19 17:05:06,576 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():628] backend started and connected
2024-02-19 17:05:06,588 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 17:05:06,588 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 17:05:06,588 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():720] updated telemetry
2024-02-19 17:05:06,597 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 17:05:06,779 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 17:05:06,806 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 17:05:06,807 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 17:05:10,723 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 17:05:10,724 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 17:05:10,724 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 17:05:10,724 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 17:05:10,725 INFO    Thread-37 (_run_job):23829 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 17:05:10,784 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_config_callback():1343] config_cb None None {'trainable_params': 55803, 'non_trainable_params': 0, 'total_params': 55803}
2024-02-19 17:05:10,915 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_finish():1970] finishing run khadgaa/DL_A2_Arch2_cls/f1j1yu4d
2024-02-19 17:05:10,915 INFO    Thread-37 (_run_job):23829 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 17:05:10,915 INFO    Thread-37 (_run_job):23829 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 17:05:10,915 INFO    Thread-37 (_run_job):23829 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 17:05:10,915 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 1
2024-02-19 17:05:10,915 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_restore():2193] restore
2024-02-19 17:05:10,916 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_restore():2199] restore done
2024-02-19 17:05:17,370 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 17:05:17,372 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 17:05:17,376 INFO    Thread-37 (_run_job):23829 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 17:05:17,410 ERROR   MainThread:23829 [pyagent.py:_run_jobs_from_queue():236] Run 269qkpua errored:
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/wandb/agents/pyagent.py", line 308, in _run_job
    self._function()
  File "/tmp/ipykernel_23829/1136002265.py", line 36, in cross_validate
    history = train_sweep_arch2(
  File "/tmp/ipykernel_23829/2550959825.py", line 45, in train_sweep_arch2
    history = train(
  File "/tmp/ipykernel_23829/2815199032.py", line 40, in train
    output = model(input)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_23829/4031563196.py", line 178, in forward
    x = self.cnn_features(x)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/ipykernel_23829/4031563196.py", line 19, in forward
    x = self.conv1(x)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 564.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 185.06 MiB is free. Process 70288 has 14.56 GiB memory in use. Of the allocated memory 14.40 GiB is allocated by PyTorch, and 36.14 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

